package io.github.geniot.jnovelist.view;

import io.github.geniot.jnovelist.*;
import io.github.geniot.jnovelist.actions.CommitterTask;
import io.github.geniot.jnovelist.actions.LoadNovelAction;
import io.github.geniot.jnovelist.model.Chapter;
import io.github.geniot.jnovelist.model.JNovel;
import io.github.geniot.jnovelist.model.Part;

import javax.swing.*;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URI;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class JNovelistApplication extends DesktopApplication {
    private JPanel contentPanel;
    private JButton loadButton;
    public JPanel partsPanel;
    public JPanel chaptersPanel;
    public JPanel editorPanel;
    private JPanel tabsPanel;
    public JButton unloadButton;
    private JButton gitButton;
    private JButton preferencesButton;
    private JButton infoButton;
    private JPanel toolbarPanel;
    private JButton exportButton;
    private JButton dictionaryButton;

    public JNovel novel;
    public String path;
    public CommitterTask committerTask;
    public ChapterEditor chapterEditor;

    private final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
        toolbarPanel = new JPanel();
        toolbarPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        contentPanel.add(toolbarPanel, BorderLayout.NORTH);
        loadButton = new JButton();
        loadButton.setFocusPainted(false);
        loadButton.setFocusable(false);
        loadButton.setIcon(new ImageIcon(getClass().getResource("/images/Load.png")));
        loadButton.setMaximumSize(new Dimension(40, 40));
        loadButton.setMinimumSize(new Dimension(40, 40));
        loadButton.setPreferredSize(new Dimension(40, 40));
        loadButton.setText("");
        toolbarPanel.add(loadButton);
        gitButton = new JButton();
        gitButton.setEnabled(false);
        gitButton.setFocusPainted(false);
        gitButton.setFocusable(false);
        gitButton.setIcon(new ImageIcon(getClass().getResource("/images/Save.png")));
        gitButton.setMaximumSize(new Dimension(40, 40));
        gitButton.setMinimumSize(new Dimension(40, 40));
        gitButton.setPreferredSize(new Dimension(40, 40));
        gitButton.setText("");
        toolbarPanel.add(gitButton);
        exportButton = new JButton();
        exportButton.setBorderPainted(true);
        exportButton.setEnabled(true);
        exportButton.setFocusPainted(false);
        exportButton.setFocusable(false);
        exportButton.setIcon(new ImageIcon(getClass().getResource("/images/Export.png")));
        exportButton.setMaximumSize(new Dimension(40, 40));
        exportButton.setMinimumSize(new Dimension(40, 40));
        exportButton.setPreferredSize(new Dimension(40, 40));
        exportButton.setRequestFocusEnabled(false);
        exportButton.setText("");
        toolbarPanel.add(exportButton);
        unloadButton = new JButton();
        unloadButton.setEnabled(false);
        unloadButton.setFocusPainted(false);
        unloadButton.setFocusable(false);
        unloadButton.setIcon(new ImageIcon(getClass().getResource("/images/Unload.png")));
        unloadButton.setMaximumSize(new Dimension(40, 40));
        unloadButton.setMinimumSize(new Dimension(40, 40));
        unloadButton.setPreferredSize(new Dimension(40, 40));
        unloadButton.setText("");
        toolbarPanel.add(unloadButton);
        preferencesButton = new JButton();
        preferencesButton.setBorderPainted(true);
        preferencesButton.setEnabled(true);
        preferencesButton.setFocusPainted(false);
        preferencesButton.setFocusable(false);
        preferencesButton.setIcon(new ImageIcon(getClass().getResource("/images/Style.png")));
        preferencesButton.setMaximumSize(new Dimension(40, 40));
        preferencesButton.setMinimumSize(new Dimension(40, 40));
        preferencesButton.setPreferredSize(new Dimension(40, 40));
        preferencesButton.setRequestFocusEnabled(false);
        preferencesButton.setText("");
        toolbarPanel.add(preferencesButton);
        infoButton = new JButton();
        infoButton.setBorderPainted(true);
        infoButton.setEnabled(true);
        infoButton.setFocusPainted(false);
        infoButton.setFocusable(false);
        infoButton.setIcon(new ImageIcon(getClass().getResource("/images/Info.png")));
        infoButton.setMaximumSize(new Dimension(40, 40));
        infoButton.setMinimumSize(new Dimension(40, 40));
        infoButton.setPreferredSize(new Dimension(40, 40));
        infoButton.setRequestFocusEnabled(false);
        infoButton.setText("");
        toolbarPanel.add(infoButton);
        dictionaryButton = new JButton();
        dictionaryButton.setBorderPainted(true);
        dictionaryButton.setEnabled(true);
        dictionaryButton.setFocusPainted(false);
        dictionaryButton.setFocusable(false);
        dictionaryButton.setIcon(new ImageIcon(getClass().getResource("/images/Dictionary.png")));
        dictionaryButton.setMaximumSize(new Dimension(40, 40));
        dictionaryButton.setMinimumSize(new Dimension(40, 40));
        dictionaryButton.setPreferredSize(new Dimension(40, 40));
        dictionaryButton.setRequestFocusEnabled(false);
        dictionaryButton.setText("");
        toolbarPanel.add(dictionaryButton);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        contentPanel.add(panel1, BorderLayout.CENTER);
        tabsPanel = new JPanel();
        tabsPanel.setLayout(new BorderLayout(0, 0));
        panel1.add(tabsPanel, BorderLayout.NORTH);
        partsPanel = new JPanel();
        partsPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        tabsPanel.add(partsPanel, BorderLayout.NORTH);
        chaptersPanel = new JPanel();
        chaptersPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        tabsPanel.add(chaptersPanel, BorderLayout.SOUTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.CENTER);
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        editorPanel = new JPanel();
        editorPanel.setLayout(new BorderLayout(0, 0));
        panel2.add(editorPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

    public enum Prop {
        SELECTED_PART,
        SELECTED_CHAPTER
    }

    protected LoadNovelAction loadNovelAction;

    public JNovelistApplication() {
        super();
        committerTask = new CommitterTask(this);
        scheduler.scheduleAtFixedRate(committerTask, 5, 5, TimeUnit.SECONDS);
        getContentPane().add(contentPanel, BorderLayout.CENTER);

        toolbarPanel.setLayout(new WrapLayout(WrapLayout.LEFT, 5, 5));
        chaptersPanel.setLayout(new WrapLayout(WrapLayout.LEFT, 5, 5));
        partsPanel.setLayout(new WrapLayout(WrapLayout.LEFT, 5, 5));

        tabsPanel.setVisible(false);

        loadNovelAction = new LoadNovelAction(this);
        loadButton.addActionListener(loadNovelAction);

        unloadButton.addActionListener(e -> {
            chapterEditor = null;
            preferences.remove(LoadNovelAction.Prop.LAST_OPEN_FILE.name());
            committerTask.save(true, true);
        });

        gitButton.addActionListener(e -> committerTask.save(true, false));

        preferencesButton.addActionListener(e -> new PreferencesDialog(JNovelistApplication.this).setVisible(true));

        infoButton.addActionListener(e -> {
            try {
                Desktop.getDesktop().browse(URI.create("https://github.com/geniot/jnovelist"));
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        });

        exportButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new ExportDialog(JNovelistApplication.this).setVisible(true);
            }
        });

        dictionaryButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new DictionaryDialog(JNovelistApplication.this).setVisible(true);
            }
        });

        pack();

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                loadNovelAction.loadLast();
            }
        });
    }

    @Override
    public void onWindowClosing() {
        committerTask.save(true, true);
    }

    public void setNovel(JNovel n, String p) {
        this.novel = n;
        this.path = p;

        partsPanel.removeAll();
        chaptersPanel.removeAll();
        editorPanel.removeAll();

        if (novel == null) {
            setTitle("JNovelist");

            tabsPanel.setVisible(false);
            unloadButton.setEnabled(false);
            gitButton.setEnabled(false);
            exportButton.setEnabled(false);

        } else {
            setTitle(path);
            preferences.put(LoadNovelAction.Prop.LAST_OPEN_FILE.name(), path);

            tabsPanel.setVisible(true);
            unloadButton.setEnabled(true);
            gitButton.setEnabled(true);
            exportButton.setEnabled(true);

            int partCounter = 1;
            ButtonGroup partsButtonGroup = new ButtonGroup();
            for (Part part : novel.getParts()) {
                PartButton partButton = new PartButton(partCounter, part, novel, this);
                ++partCounter;
                partsButtonGroup.add(partButton);
                partsPanel.add(partButton);
            }
            PlusButton partPlusButton = new PlusButton();
            partsPanel.add(partPlusButton);
            partPlusButton.addActionListener(e -> {
                Part newPart = new Part();
                novel.getParts().add(newPart);
                PartButton partButton = new PartButton(partsPanel.getComponentCount(), newPart, novel, JNovelistApplication.this);
                partsButtonGroup.add(partButton);
                partsPanel.add(partButton, partsPanel.getComponentCount() - 1);
                partButton.doClick();
            });
            selectPart();
        }
    }

    public void setPart(Part part) {
        chaptersPanel.removeAll();
        int chapterCounter = 1;
        ButtonGroup chaptersButtonGroup = new ButtonGroup();
        for (Chapter chapter : part.getChapters()) {
            ChapterButton chapterButton = new ChapterButton(chapterCounter, chapter, part, this);
            ++chapterCounter;
            chaptersButtonGroup.add(chapterButton);
            chaptersPanel.add(chapterButton);
        }
        PlusButton chapterPlusButton = new PlusButton();
        chapterPlusButton.addActionListener(e -> {
            Chapter newChapter = new Chapter();
            part.getChapters().add(newChapter);
            ChapterButton chapterButton = new ChapterButton(chaptersPanel.getComponentCount(), newChapter, part, JNovelistApplication.this);
            chaptersButtonGroup.add(chapterButton);
            chaptersPanel.add(chapterButton, chaptersPanel.getComponentCount() - 1);
            chapterButton.doClick();
        });
        chaptersPanel.add(chapterPlusButton);

        selectChapter();
    }

    public void setChapter(Chapter chapter) {
        if (chapterEditor == null) {
            chapterEditor = new ChapterEditor(chapter, this);
            chapterEditor.setBorder(new LineBorder(Color.BLACK));
            editorPanel.add(chapterEditor, BorderLayout.CENTER);
        } else {
            chapterEditor.setChapter(chapter);
        }
        invalidate();
        validate();
        repaint();
    }

    public void selectChapter() {
        int selectedChapter = preferences.getInt(Prop.SELECTED_CHAPTER.name(), 1);
        if (selectedChapter > chaptersPanel.getComponentCount() - 1) {
            selectedChapter = chaptersPanel.getComponentCount() - 1;
        }
        ((ChapterButton) chaptersPanel.getComponent(selectedChapter - 1)).doClick();
    }

    public void selectPart() {
        int selectedPart = preferences.getInt(Prop.SELECTED_PART.name(), 1);
        if (selectedPart > partsPanel.getComponentCount() - 1) {
            selectedPart = partsPanel.getComponentCount() - 1;
        }
        ((PartButton) partsPanel.getComponent(selectedPart - 1)).doClick();
    }
}
